name: push

on:
  push:
    branches:
      - main

jobs:
  build_installer:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ "3.10" ]
    if: github.ref == 'refs/head/main'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for Pybinding
        run: python -m pip install -r requirements.txt
      - name: Build with python
        timeout-minutes: 4
        run: python.exe .\generate.py interface
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.exe
