name: push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for Pybinding
        run: python -m pip install -r requirements.txt
      - name: Build with python
        timeout-minutes: 4
        run: python .\generate.py interface
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload:
    name: Upload on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]
    needs: [ build ]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Obtain installer version
        run: |
          INSTALLER_VERSION=$(python -c "import json;jf=open('resources/config.json','r');print(json.load(jf)['installer_version']);jf.close()")
          echo $INSTALLER_VERSION >> dist/version
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.t }}
      - name: Upload to Minelabs-server
        run: ./.github/scripts/sftp_upload.sh
        shell: bash